use_frameworks!

platform :ios, '8.0'

target 'WAHealthDataManager_Example' do
  pod 'WAHealthDataManager', :path => '../'

  target 'WAHealthDataManager_Tests' do
    inherit! :search_paths

    
  end
end
